= Portfolio of `gardrek`
:toc:

== Fonts

More fonts are coming soon-ish.

[[ldeeds_h]]
=== Legendary Deeds

My first released font, https://gardrek.itch.io/legendary-deeds[Legendary Deeds] is a proportional serif pixel font with wide coverage of languages written using the Latin, Greek, and Cyrillic scripts.


== Interpreters, Assemblers, and Other Programming Platforms

[[bollox_h]]
=== Lox Language Implementation

https://github.com/gardrek/bollox[`bollox`] is an interpreter for the language Lox, written in Rust, with various feature extensions. It is based on the first interpreter described by the book Crafting Interpreters. That interpreter was written in Java, so a good deal of changes have been made to the structure to make it more "`Rusty`", and to enable the addition of a few extra features of my own design.


[[lxsp_h]]
=== LXSP, a Minimal LISP Implementation

https://github.com/gardrek/lxsp[`lxsp`] is a minimal LISP implementation written in Rust.


[[protoplasm]]
=== ProtoplASM, a Configurable Assembler

https://github.com/gardrek/protoplasm[ProtoplASM] is a configurable assembler designed for hobby CPU architectures.


[[vvpet_h]]
=== VVpet, a Tool for Creating Virtual Pet Games for PC

https://gardrek.itch.io/vvpet[VVpet] is a system for making and playing virtual pets inspired by Tamagotchi and Digimon: Digital Monsters. It allows one to easily make their own fantasy consoles, as well as games for those consoles, and comes with a default console for which one can immediately start programming in Lua. Source is available https://github.com/gardrek/vvpet[on Github at this link].


== Games

=== Blob Tower

https://gardrek.itch.io/wgj53[Blob Tower] is a short game/demo I made for a week-long game jam in July 2018. It was made with LÖVE, and is one of my first fully completed game projects.
